services:
  - type: web
    name: youtube-extractor
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install curl-cffi
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: "true"
